version: '3'
services:
  node: 
    image: node-image
    build: ./api
    command: node app.js
    ports:
    - "3000:3000"
    volumes:
    - ./api:/usr/src/app
    - /usr/src/app/node_modules
    links: 
    - mongo
    environment:
    - MONGO_URI=mongodb://api:password@mongo

  mongo:
    image: "mongo"
    ports: 
    - "27017:27017"
    volumes: 
    - ./db:/data/db
    environment: 
    - MONGO_INITDB_ROOT_USERNAME=api
    - MONGO_INITDB_ROOT_PASSWORD=password
    
  mongoAdmin:
    image: "mrvautin/adminmongo"
    ports:
    - "1234:1234"
    environment:
    - HOST=0.0.0.0
    links: 
    - 'mongo:mongo'
